server {

  listen 8581; # слушаем обращения к порту 7520
  server_name 178.172.195.18; # к сайту вот с таким именем

  # перебиваем дефолтные директивы access_log и error_log, заданные на уровне nginx.conf
  access_log /home/user/homework/it-academy-project/nginx-access.log main;  # в какой файл и в каком формате (main) логгируются успешные обращения
  error_log  /home/user/homework/it-academy-project/nginx-error.log  error; # в какой файл и в каком формате (error, встроенный) логгируются ошибки

  location / { # обращения к любым УРЛам, содержащим "/" (а то есть к любым вообще)
    root /home/user/homework/it-academy-project/static; # обслуживаем как статику из этой папки
  }

}
