server {

  listen 8580;
  server_name 178.172.195.18;

  access_log /home/user/homework/it-academy-project/nginx-access.log main;
  error_log  /home/user/homework/it-academy-project/nginx-error.log  error;

  location ^~ / {
    proxy_pass http://localhost:8581;

    location ~* \.(PNG|JPG|GIF|SVG|JPE|JS|CSS|HTML|png|jpg|gif|svg|jpe|js|css|html)$ {
       root /home/user/homework/it-academy-project/static;
        expires max;
    }

  }

  access_log /home/user/homework/it-academy-project/nginx-proxy.log proxy;

}
